I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 20, in script
    scene black screen
Exception: Image 'black' does not accept attributes 'screen'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 20, in script
    scene black screen
  File "C:\Users\MIGUEL CAMPOS\Downloads\renpy-8.3.2-sdk\renpy\ast.py", line 1245, in execute
    show_imspec(self.imspec, atl=getattr(self, "atl", None))
  File "C:\Users\MIGUEL CAMPOS\Downloads\renpy-8.3.2-sdk\renpy\ast.py", line 1074, in show_imspec
    renpy.config.show(name,
  File "C:\Users\MIGUEL CAMPOS\Downloads\renpy-8.3.2-sdk\renpy\exports\displayexports.py", line 477, in show
    if not base.find_target() and renpy.config.missing_show:
  File "C:\Users\MIGUEL CAMPOS\Downloads\renpy-8.3.2-sdk\renpy\display\image.py", line 421, in find_target
    self.target = target._duplicate(a)
  File "C:\Users\MIGUEL CAMPOS\Downloads\renpy-8.3.2-sdk\renpy\display\displayable.py", line 249, in _duplicate
    args.extraneous()
  File "C:\Users\MIGUEL CAMPOS\Downloads\renpy-8.3.2-sdk\renpy\display\displayable.py", line 109, in extraneous
    raise Exception("Image '{}' does not accept attributes '{}'.".format(
Exception: Image 'black' does not accept attributes 'screen'.

Windows-10-10.0.19041 AMD64
Ren'Py 8.3.2.24090902
OS Date Sim 1.0
Wed Oct  2 23:13:50 2024
